CREATE TABLE REST_MEMBER (
	MEM_ID VARCHAR(10) PRIMARY KEY,
	MEM_NAME VARCHAR(10) NOT NULL,
	MEM_AGE INT DEFAULT 0,
	MEM_TEL VARCHAR(15) UNIQUE
);

SELECT * FROM REST_MEMBER;

INSERT INTO REST_MEMBER(MEM_ID,MEM_NAME,MEM_AGE,MEM_TEL)
		 VALUES ("IDA","KIM",20,"010-1234-5678");
INSERT INTO REST_MEMBER 
		 VALUES ("IDB","LEE",25,"010-9999-5555");
INSERT INTO REST_MEMBER
		 VALUES ("IDC","SONG",15,"010-8000-9547");
INSERT INTO REST_MEMBER
		 VALUES ("IDD","JI",35,"010-3691-0258");

COMMIT;

#회원 한명의 모든 컬럼 정보를 조회
SELECT *
FROM rest_member
WHERE mem_id = 'IDA';

#아이디는 IDC고 나이는 15살 인거 조회하기
SELECT *
FROM REST_MEMBER
WHERE MEM_ID = 'IDC'
AND MEM_AGE = 15;

#회원정보 등록
INSERT INTO REST_MEMBER(MEM_ID,MEM_NAME,MEM_AGE,MEM_TEL)
		 VALUES ("IDE","CHA",28,"010-7410-9630");
		 
# 게시글 정보 테이블
CREATE TABLE REST_BOARD(
  BOARD_NUM INT PRIMARY KEY, 
  TITLE VARCHAR(10) NOT NULL,
  CONTENT VARCHAR(20),
  WRITER VARCHAR(10) 
);

INSERT INTO REST_BOARD VALUES (1,"제목1","내용1","LEE");
INSERT INTO REST_BOARD VALUES (2,"제목2","내용2","LEE");
INSERT INTO REST_BOARD VALUES (3,"제목3","내용3","LEE");

SELECT * FROM REST_BOARD;

COMMIT;

# 상품
CREATE TABLE REST_ITEM(
  ITEM_CODE INT PRIMARY KEY AUTO_INCREMENT,
  ITEM_NAME VARCHAR(30) NOT NULL,
  ITEM_PRICE INT DEFAULT 0,
  ITEM_COLOR VARCHAR(20)
);

INSERT INTO REST_ITEM (ITEM_NAME,ITEM_PRICE,ITEM_COLOR)
		 VALUES ("후드티",10000,"노랑");
INSERT INTO REST_ITEM (ITEM_NAME,ITEM_PRICE,ITEM_COLOR)
		 VALUES ("청바지티",30000,"파랑");
INSERT INTO REST_ITEM (ITEM_NAME,ITEM_PRICE,ITEM_COLOR)
		 VALUES ("롱패딩",60000,"검정");
INSERT INTO REST_ITEM (ITEM_NAME,ITEM_PRICE,ITEM_COLOR)
		 VALUES ("반팔티",20000,"초록");

SELECT * FROM REST_ITEM;

ROLLBACK;