#상품정보 테이블
CREATE TABLE ITEM_INFO (
 ITEM_NUM INT AUTO_INCREMENT PRIMARY KEY-- 상품번호
, ITEM_NAME VARCHAR(50) NOT NULL UNIQUE-- 상품명
, ITEM_PRICE INT NOT NULL-- 상품가격
, SELLER VARCHAR(30) NOT NULL-- 판매자
, ITEM_INTRO VARCHAR(100)-- 상품 설명
, REG_DATE DATETIME DEFAULT SYSDATE()
 );
 
 CREATE TABLE ORDER_INFO (
 ORDER_NUM INT AUTO_INCREMENT PRIMARY KEY-- 주문번호
, ITEM_NUM INT NOT NULL REFERENCES ITEM_INFO (ITEM_NUM)
, BUYER VARCHAR(50) NOT NULL-- 구매자
, BUY_CNT INT NOT NULL-- 구매 수량
, BUY_PRICE INT NOT NULL-- 구매 가격 (단가 * 수량)
, BUY_DATE DATETIME DEFAULT SYSDATE()
 );
 
 SELECT * FROM order_info;