deptSELECT * FROM react_member;

COMMIT;
#회원관리 테이블
CREATE TABLE REACT_MEMBER(
	 MEM_ID VARCHAR(10) PRIMARY KEY
	,MEM_NAME VARCHAR(10) NOT NULL
	,MEM_PW VARCHAR(10) NOT NULL
	,MEM_TELL VARCHAR(15) UNIQUE
	,MEM_INTRO VARCHAR(30)
	,JOIN_DATE DATETIME DEFAULT SYSDATE()
);

INSERT INTO REACT_MEMBER
		 VALUES('java','김자바','1111','010-1111-1111','안녕 난 김자바라고해',NOW());

UPDATE REACT_MEMBER
SET	MEM_NAME = '{memName}'
    , MEM_PW = '{memPw}'
    , MEM_TELL = '{memTell}'
    , MEM_INTRO = '{memIntro}'
WHERE MEM_ID = '#{memId}';

DELETE FROM react_member
WHERE MEM_ID = ' ';