-- 연습용 자동차 정보 테이블
CREATE TABLE TEST_CAR (
	-- 시험시험
	MODEL_NUMBER INT PRIMARY KEY,
	MODEL_NAME VARCHAR(20),
	COLOR VARCHAR(20),
	PRICE INT,
	BRAND VARCHAR(20)
);

SELECT * FROM TEST_CAR;

CREATE TABLE BOARD(
	BOARD_NUM INT PRIMARY KEY,
	TITLE VARCHAR(40) NOT NULL,
	WRITER VARCHAR(16) NOT NULL,
	READ_CNT INT DEFAULT 0
);

SELECT * FROM BOARD;

-- 테이블 삭제 답이없서
DROP TABLE BOARD;

-- 데이터 삽입
-- INSERT INTO 테이블명(컬럼,컬럼...) VALUES (데이터,데이터....);
INSERT INTO BOARD (BOARD_NUM,TITLE,WRITER,READ_CNT)
VALUES(1,'안녕이라고 말하지마','김자바',0);

INSERT INTO BOARD (BOARD_NUM,TITLE,WRITER,READ_CNT)
VALUES(2,'제목2란말이다','박자바',50);

INSERT INTO BOARD (BOARD_NUM,TITLE,WRITER,READ_CNT)
VALUES(3,'제목5란말이다','박자바',40);

INSERT INTO BOARD (BOARD_NUM,TITLE,WRITER,READ_CNT)
VALUES(4,'제목5란말이다','박자바',40);

INSERT INTO BOARD (BOARD_NUM,TITLE,WRITER,READ_CNT)
VALUES(5,'제목5란말이다','박자바',40);

INSERT INTO BOARD (BOARD_NUM,TITLE,WRITER)
VALUES(6,'제목5란말이다','박자바');

INSERT INTO BOARD VALUES(11,'시빌시빌시빌비실와','송자바',0);

COMMIT;
ROLLBACK;
