# 테이블을 만들어줄거임 회원정보`member`
CREATE TABLE MEMBER(
	MEM_ID VARCHAR(20) PRIMARY KEY
	,MEM_PW VARCHAR(20) NOT NULL
	,MEM_NAME VARCHAR(10)
	,MEM_AGE INT DEFAULT 1
	,MEME_TELL VARCHAR(12) UNIQUE 
	,JOIN_DATE DATETIME DEFAULT SYSDATE()
);

# 시스템데이트 : 현재날자
SELECT SYSDATE(), NOW();

SELECT * FROM member;

INSERT INTO member (MEM_ID,MEM_PW)
VALUES ('GONG','1111');

INSERT INTO member (MEM_ID,MEM_PW,MEM_NAME,JOIN_DATE)
VALUES ('KIM','1524','김이름','2025-01-01');

INSERT INTO member (MEM_ID,MEM_PW,MEM_NAME,JOIN_DATE)
VALUES ('LEE','554554','이길동','2025-01-01 10:30:50');

INSERT INTO member (MEM_ID,MEM_PW,MEM_NAME,JOIN_DATE)
VALUES ('SONG','554554','이길동',20241224000530);

COMMIT;

# 데이터 삭제쿼리
# DROP FROM (테이블명)  테이블 토ㅇ삭제 
# DELETE FROM (테이블명) WHERE 
DELETE FROM member;

ROLLBACK;

DELETE FROM member WHERE MEM_NAME IS NULL;

#데이터수정
# UPDATE TABLE 테이블명 SET 컬럼=바꿀값,컬럼바꿀값 WHERE조건;
UPDATE member
SET
MEM_NAME = '홍길동',MEM_AGE = 58 WHERE MEM_ID = 'LEE';