CREATE TABLE BASIC_BOARD(
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	,TITLE VARCHAR(30) NOT NULL
	,WRITER VARCHAR(20)
	,CONTENT VARCHAR(50)
	,READ_CNT INT DEFAULT 0
	,CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM BASIC_BOARD;
# ㅇㅋ 잘뜸

INSERT INTO BASIC_BOARD(TITLE,WRITER,CONTENT) VALUES("제목1","작성자1","내~~~~~~~용1");
INSERT INTO BASIC_BOARD(TITLE,WRITER,CONTENT,READ_CNT,CREATE_DATE) VALUES("제목2","작성자2","내~~~~~~~용2",5,"2025-02-04");

COMMIT;

SELECT * FROM basic_board
WHERE board_num = 1;