#상품정보 테이블
CREATE TABLE ITEM_INFO (
 ITEM_NUM INT AUTO_INCREMENT PRIMARY KEY-- 상품번호
, ITEM_NAME VARCHAR(50) NOT NULL UNIQUE-- 상품명
, ITEM_PRICE INT NOT NULL-- 상품가격
, SELLER VARCHAR(30) NOT NULL-- 판매자
, ITEM_INTRO VARCHAR(100)-- 상품 설명
, REG_DATE DATETIME DEFAULT SYSDATE()
 );
 
 CREATE TABLE ORDER_INFO (
 ORDER_NUM INT AUTO_INCREMENT PRIMARY KEY-- 주문번호
, ITEM_NUM INT NOT NULL REFERENCES ITEM_INFO (ITEM_NUM)
, BUYER VARCHAR(50) NOT NULL-- 구매자
, BUY_CNT INT NOT NULL-- 구매 수량
, BUY_PRICE INT NOT NULL-- 구매 가격 (단가 * 수량)
, BUY_DATE DATETIME DEFAULT SYSDATE()
 );
 
  SELECT * FROM board;
 SELECT * FROM board_reply;
 
 # 묘사하다 설명하다 구조보기
 DESC order_info;
 
 CREATE TABLE REACT_DEPT(
 	dept_NO INT PRIMARY KEY AUTO_INCREMENT
 	,DEPT_NAME VARCHAR(20) NOT NULL
 );
 
  CREATE TABLE REACT_JOB(
 	JOB_NO INT PRIMARY KEY AUTO_INCREMENT
 	,JOB_NAME VARCHAR(20) NOT NULL
 );
 
 CREATE TABLE REACT_EMP(
 	EMP_NO INT PRIMARY KEY AUTO_INCREMENT
 	,EMP_NAME VARCHAR(20) NOT NULL
 	,GENDER VARCHAR(10)
 	,HIRE_DATE DATETIME
 	,DEPT_NO INT REFERENCES REACT_DEPT (DEPT_NO)
 	,JOB_NO INT REFERENCES REACT_JOB (JOB_NO)
 );
 
 #boardreply의 컬럼명변경
  ALTER TABLE board_reply CHANGE COLUMN writer REPLY_writer VARCHAR(20) ;
  ALTER TABLE board_reply CHANGE COLUMN reg_date REPLY_reg_date DATETIME DEFAULT SYSDATE(); ;
 ALTER TABLE board_reply CHANGE COLUMN CONTENT REPLY_CONTENT VARCHAR(20) ;
 
 #모든게시글의 게시글 번호 제목 작성자 및 게시글의 달린 댓글 내용,작성자 조회
 SELECT b.BOARD_NUM
 		,title
 		,writer
		,reply_content
		,reply_writer
		FROM board b LEFT outer join board_reply r
		ON b.board_num = r.board_num;
		
		